common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordChangeView
from . import views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('editinfo/', views.editinfo, name='editinfo'),

    #editpw, changed 추가 (5.28)
    path('editpw/', PasswordChangeView.as_view(template_name = 'common/editpw.html', success_url = '/common/changed'), name='editpw'),
    path('changed/', views.changed, name='changed')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
# 이미지
from django.conf.urls.static import static
from django.conf import settings

from . import views


from django.conf.urls.static import static
urlpatterns = [
    path('',views.index),
    path('admin/', admin.site.urls),
    path('share/', include('share.urls')),
    path('common/', include('common.urls'))
]


# 이미지업로드관련
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

share/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'share'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:Post_id>/', views.detail, name='detail'),
    
    
    path('create/', views.create, name="create"),
    path('cart/', views.cart, name="cart"),
    path('joined/', views.joined, name="joined"),
    path('join/<int:Post_id>/', views.join, name="join"),
    path('like/<int:Post_id>/', views.like, name="like"),
    
    path('modify/<int:Post_id>/', views.modify, name="modify"),
    path('Delete/<int:Post_id>/', views.Delete, name="Delete"),
    
    path('category/<int:category_num>/', views.category, name='category'),

]

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name","password1", "password2", "email")

#회원정보 수정할 때
class editInfoForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
        )

# PasswordChangeForm2 추가 (5.27) -> 근데 안쓸듯?
class PasswordChangeForm2(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm2, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = 'Old Password'
        self.fields['old_password'].widget.attrs.update({'class': 'form-control'})
        self.fields['new_password1'].label = 'New Password'
        self.fields['new_password1'].widgets.attrs.update({'class': 'form-control'})
        self.fields['new_password2'].label = 'Confirm New Password'
        self.fields['new_password2'].widgets.attrs.update({'class': 'form-control'})

common/views.py
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from . forms import editInfoForm
from django.http import HttpResponse

#PasswordChangeForm2 불러옴 (5.27) -> 근데 안쓸듯?
from . forms import editInfoForm, PasswordChangeForm2



def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('/share/')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


def editinfo(request):
    if request.method == 'POST':
        form = editInfoForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/common/changed')
    else:
        form = editInfoForm(instance=request.user)
        context = {'form': form}
        return render(request, 'common/editinfo.html', context)

#PasswordChangeView.as_view 쓰니까 안써도 되는 듯?
""" def editpw(request):
    if request.method == 'POST':
        pwform = PasswordChangeForm(data=request.POST, user=request.user)
        if pwform.is_valid():
            pwform.save()
            return redirect('/share')
    else:
        pwform = PasswordChangeForm(user=request.user)
        context = {'form': pwform}
        return render(request, 'common/editpw.html', context) """

# editpw2 (5.28) -> PasswordChangeView.as_view 쓰니까 안써도 되는 듯?
""" def editpw2(request):
    if request.method == 'POST':
        pwform2 = PasswordChangeForm2(request.user, request.POST)
        if pwform2.is_valid():
            user = pwform2.save()
            #update_session_auth_hash(request, user)
            #messages.success(request, "Password has been hanged.")
            return redirect('/share')
    else:
        pwform2 = PasswordChangeForm2(request.user)
    return render(request, 'common/editpw.html', {'pwform2': pwform2}) """

#회원정보나 비밀번호 수정하고 나면 가게 되는 주소
def changed(request):
    return render(request, 'common/changed.html')

templates/common/changed.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'joined-style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Grape+Nuts&display=swap" rel="stylesheet">
    <title>Success</title>
</head>
<body>
    <div class="sideNav" style="top:0; left:0">
        <header>My Page</header>
        <img src="{% static 'images/user.png' %}" alt="" id="userImg">
        <ul>
            <li><a href="/share/" id="pagename">Home</a></li>
            <li><a href="{% url 'share:joined' %}" id="joined">Joined Group</a></li>
            <li><a href="{% url 'share:joined' %}">Created Group</a></li>
            <li><a href="{% url 'common:editinfo' %}">Edit Information</a></li>
            <li><a href="{% url 'common:editpw' %}">Edit Password</a></li>
            {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'common:logout' %}">logout</a></li>
            {% endif %}     
        </ul>
    </div>
    <div class="contents">
        <h1>Succesfully Changed</h1>
    </div>
</body>
</html>

templates/common/editinfo.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'joined-style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Grape+Nuts&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'edit-info.css' %}?after">
    <title>Edit Your Information</title>
</head>
<body>
    <div class="sideNav" style="top:0; left:0">
        <header>My Page</header>
        <img src="{% static 'images/user.png' %}" alt="" id="userImg">
        <ul>
            <li><a href="/share/" id="pagename">Home</a></li>
            <li><a href="{% url 'share:joined' %}" id="joined">Joined Group</a></li>
            <li><a href="{% url 'share:cart' %}">Created Group</a></li>
            <li><a href="{% url 'common:editinfo' %}"><b>Edit Information</b></a></li>
            <li><a href="{% url 'common:editpw' %}">Edit Password</a></li>
            {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'common:logout' %}">logout</a></li>
            {% endif %}     
        </ul>
    </div>
    <div class="contents">
        <h1>Edit Your Information</h1>
        <form method="POST">
            {% csrf_token %}

            {% for error in form.non_field_errors %}
                <div class="editpw-error">
                    {{ error }}
                </div>
            {% endfor %}

            {% for field in form %}
                <div class="editpw-label">
                    {{ field.label }}
                </div>

                <div class="editinfo-field">
                    {{ field }}
                </div>

                {% if field.errors %}
                <div class="editpw-error">
                    {{ field.errors }}
                </div>
                {% endif %}
            {% endfor%}
            <p id="editinfo-description">You can change password from the navigation bar on the left.</p>
            <button type="submit">Edit</button>
        </form>
    </div>
</body>
</html>

templates/common/editpw.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="myPage.css">
    <link rel="stylesheet" href="joined.css">
    <link rel="stylesheet" href="home.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Grape+Nuts&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'joined-style.css' %}?after">
    <link rel="stylesheet" type="text/css" href="{% static 'edit-info.css' %}?after">

    <title>Edit Password</title>
</head>
<body>
    <div class="sideNav" style="top:0; left:0">
        <header>My Page</header>
        <img src="{% static 'images/user.png' %}" alt="" id="userImg">
        <ul>
            <li><a href="/share/" id="pagename">Home</a></li>
            <li><a href="{% url 'share:joined' %}" id="joined">Joined Group</a></li>
            <li><a href="{% url 'share:cart' %}">Created Group</a></li>
            <li><a href="{% url 'common:editinfo' %}">Edit Information</a></li>
            <li><a href="{% url 'common:editpw' %}"><b>Edit Password</b></a></li>
            {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'common:logout' %}">logout</a></li>
            {% endif %}     
        </ul>
    </div>
    <div class="contents">
        <h2>Change Password</h2>
        <form method="POST">
            {% csrf_token %}

            {% for error in form.non_field_errors %}
                <div class="editpw-error">
                    {{ error }}
                </div>
            {% endfor %}

            {% for field in form %}
                <div class="editpw-label">
                    {{ field.label }}
                </div>

                <div class="editpw-field">
                    {{ field }}
                </div>

                {% if field.errors %}
                <div class="editpw-error">
                    {{ field.errors }}
                </div>
                {% endif %}
            {% endfor%}
            <button type="submit">Edit</button>
        </form>
    </div>
</body>

templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="header.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}?after">
    <title>Login</title>
</head>

<body>
    <header>
        {% if user.is_authenticated %}
        <div id="sharebox">
            <a href="{%url 'share:create' %}" id="share"><b>LET'S<br>START</b></a>
        </div>
        {% endif %}
        <h1><a href="/share/" id="pagename">SHARESHARE</a></h1>

        <nav>
            {% if user.is_authenticated %}
            <a href="{%url 'share:joined' %}" id="joined">cart</a>
            {% endif %}
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logout' %}">LOGOUT</a>
            {% else %}
            <a class="nav-link" href="{% url 'common:login' %}">LOGIN</a>
            {% endif %}
        </nav>

    </header>

    <div id="loginbox">
        <form action="{% url 'common:login' %}" method="post" class="login" style="margin-top: 150px;">
            {% csrf_token %}
            <p style="font-size: 60px; font-weight: 100;">LOG IN</p>

            {% for field in form %}
                <div style="margin: 7px;"></div>
                <div class="form-group">
                    <input type="{{field.field.widget.input_type}}" class="form-control" id="{{field.id_for_label}}" placeholder="{{field.label}}" name="{{field.name}}">
                </div>

                <div style="margin: 7px;"></div>

                <!-- 에러 메시지가 있을 경우 출력 -->
                {% if field.errors %}
                    <span style="max-width:30%; margin:auto; color:red; text-align:left;">{{field.errors}}</span>
                {% endif %}
            {% endfor %}

            <div style="margin-top: 10px;"></div>
            <button id="loginButton" type ="submit" class = "btn btn-primary">LOG IN</button>
            <br>
            <div style="margin: 5px;"></div>
            {% if form.non_field_errors %}
                <span style="max-width:30%; margin:auto; color:red; text-align:left;">Please press the button below to proceed with the membership registration.</span>
            {% endif %}
            <br>
            <a href="{% url 'common:signup' %}" style="text-decoration: none; color: darkslategrey; margin-top: 100px;">Don't have an account?</a>

            </div>
        </form>
    </div>
        
    <div id="finish">
        <footer class="footer">
            <h1><a href="/share/" id="pagename">SHARESHARE</a></h1>
            <div>
            This is Team TAG's Project!!<br>
            최락원, 김민수, 이은서, 변승진, 이은지, 유종혁
            </div>
        </footer>
    </div>
</body>
</html>

templates/common/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta chrarset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'signup-style.css' %}?after">
    <title>Signup Page</title>
</head>

<body>
    <header>
        {% if user.is_authenticated %}
        <div id="sharebox">
            <a href="{%url 'share:create' %}" id="share"><b>LET'S<br>START</b></a>
        </div>
        {% endif %}
        <h1><a href="/share/" id="pagename">SHARESHARE</a></h1>

        <nav>
            {% if user.is_authenticated %}
            <a href="{%url 'share:joined' %}" id="joined">cart</a>
            {% endif %}
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logout' %}">LOGOUT</a>
            {% else %}
            <a class="nav-link" href="{% url 'common:login' %}">LOGIN</a>
            {% endif %}
        </nav>

    </header>


    <div id="contents">

        <p class="welcome">Welcome</p>
        <p class="explain">Buy it at a low price using a joint purchase</p>

        <form action="{% url 'common:signup' %}" method="post">
            {% csrf_token %}
            {% include "form_errors.html" %}

            <label for="myid"><b>ID</b></label> <br>
            <input type="text" placeholder="Please enter your ID" class="form-control" name="username" id="username"
            value="{{ form.username.value|default_if_none:'' }}">
            <br>
            <label for="first_name"><b>First Name</b></label> <br>
            <input type="text" placeholder="Please enter your Frist Name" class="form-control" name="first_name" id="first_name"
            value="{{form.first_name.value|default_if_none:''}}">
            <br>
            <label for="last_name"><b>lastname</b></label> <br>
            <input type="text" placeholder="Please enter your ID" class="form-control" name="last_name" id="last_name"
            value="{{ form.last_name.value|default_if_none:'' }}">
            <br>

            <label for="password1"><b>PASSWORD</b></label><br>
            <input type="password" placeholder="Please enter your Password" class="form-control" name="password1" id="password1"
            value="{{ form.password1.value|default_if_none:'' }}">
            <br>

            <label for="password2"><b>CONFIRM PASSWORD</b></label><br>
            <input type="password" placeholder="Confirm your Password" class="form-control" name="password2" id="password2"
            value="{{ form.password2.value|default_if_none:'' }}">
            <br>

            <label for="mymail"><b>EMAIL</b></label> <br>
            <input type="text" placeholder="Please enter your Email" class="form-control" name="email" id="email"
            value="{{ form.email.value|default_if_none:'' }}">
            
            <br>
            <label for="check"></label>
            <input type="checkbox" name="check"> <span  id="check">I agree to the Terms and Conditions and Privacy Policy.</span>
            
            <br>
            <br>
            <input type="submit" class="btn-primary" value="Sign up"></input>
            <br>
            <br>
        </form>


    </div>

    <div id="finish">
        <footer class="footer">
            <h1><a href="/share/" id="pagename">SHARESHARE</a></h1>
            <div>
            This is Team TAG's Project!!<br><br>
            최락원, 김민수, 이은서, 변승진, 이은지, 유종혁
            </div>
        </footer>
    </div>
</body>

</html>