common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordChangeView
from . import views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('editinfo/', views.editinfo, name='editinfo'),

    #editpw, changed 추가 (5.28)
    path('editpw/', PasswordChangeView.as_view(template_name = 'common/editpw.html', success_url = '/common/changed'), name='editpw'),
    path('changed/', views.changed, name='changed')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
# 이미지
from django.conf.urls.static import static
from django.conf import settings

from . import views


from django.conf.urls.static import static
urlpatterns = [
    path('',views.index),
    path('admin/', admin.site.urls),
    path('share/', include('share.urls')),
    path('common/', include('common.urls'))
]


# 이미지업로드관련
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

share/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'share'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:Post_id>/', views.detail, name='detail'),
    
    
    path('create/', views.create, name="create"),
    path('cart/', views.cart, name="cart"),
    path('joined/', views.joined, name="joined"),
    path('join/<int:Post_id>/', views.join, name="join"),
    path('like/<int:Post_id>/', views.like, name="like"),
    
    path('modify/<int:Post_id>/', views.modify, name="modify"),
    path('Delete/<int:Post_id>/', views.Delete, name="Delete"),
    
    path('category/<int:category_num>/', views.category, name='category'),

]

share/models.py
from django.db import models
from django.contrib.auth.models import User

# 카테고리
class Category(models.Model):
    sort = models.CharField(max_length = 255)
    def __str__(self):
        return self.sort
    
# 상품 모델
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    Modify_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=False)
    price = models.IntegerField()
    dicount_price = models.IntegerField()
    image = models.ImageField(upload_to = 'images', default='default.png', blank=True)
    recruit_num = models.IntegerField()
    participants = models.IntegerField()
    joined_users = models.ManyToManyField(User, related_name='joined_users', blank = True)
    like = models.ManyToManyField(User,related_name = 'liked_users')
    like_num = models.IntegerField(default = 0)

share/views.py
from asyncio.windows_events import NULL
import re
from django.shortcuts import render, get_object_or_404, redirect,HttpResponseRedirect
from django.utils import timezone
from pkg_resources import require
from .models import Post
from .models import Category

from django.contrib.auth import views as auth_views
from django.core.paginator import Paginator

from django.db.models import Q

from django.http import HttpResponse
from django.views.decorators.http import require_POST

# category food -> 1 book -> 2 stationery ->7 clothes -> 8 etc -> 9
def category(request, category_num):
    if category_num == 0:
        Post_list = Post.objects.order_by('-create_date')
    else :
        Post_list = Post.objects.filter(category=category_num)
    sort = request.GET.get('sort', '')
    if sort == 'like':
        Post_list = Post_list.order_by('-like_num')
    elif sort == 'Top_price':
        Post_list = Post_list.order_by('-dicount_price')
    elif sort == 'Low_price':
        Post_list = Post_list.order_by('dicount_price')
    else:
        Post_list = Post_list.order_by('-create_date')
        
    # 검색
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')  # 검색어
    if kw:
        Post_list = Post_list.filter(
            Q(title__icontains=kw)
            ).distinct()
    paginator = Paginator(Post_list, 8)
    page_obj = paginator.get_page(page)
    context = {'Post_list': page_obj,'page':page,'kw':kw}
    return render(request, 'share/main.html', context)

def like(request, Post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk = Post_id)
        if request.user in post.like.all():
            post.like.remove(request.user)
            if post.like_num != 0:
                post.like_num -=1
                post.save()
        else:
            post.like.add(request.user)
            post.like_num +=1
            post.save()
        return redirect('share:index')
    else:
        return redirect('common:login')


def index(request):
    
    # Post_list = Post.objects.filter(category=category_num)
    
    page = request.GET.get('page', '1')
    Post_list = Post.objects.order_by('-create_date')
    # 정렬
    sort = request.GET.get('sort', '')
    if sort == 'like':
        Post_list = Post_list.order_by('-like_num')
    elif sort == 'Top_price':
        Post_list = Post_list.order_by('-dicount_price')
    elif sort == 'Low_price':
        Post_list = Post_list.order_by('dicount_price')
    else:
        Post_list = Post_list.order_by('-create_date')
        
    # 검색

    kw = request.GET.get('kw', '')  # 검색어
    if kw:
        Post_list = Post_list.filter(
            Q(title__icontains=kw)
            ).distinct()
    paginator = Paginator(Post_list, 8)
    page_obj = paginator.get_page(page)
    context = {'Post_list': page_obj,'page':page,'kw':kw}
    return render(request, 'share/main.html', context)


def cart(request):
    if request.user.is_authenticated:
        Post_list = Post.objects.order_by('-create_date')
        context = {'Post_list': Post_list}
        return render(request, 'share/cart.html', context)
    else:
        return render(request, 'common/login.html')



def joined(request):

    if request.user.is_authenticated:
        Post_list = Post.objects.order_by('-create_date')
        context = {'Post_list': Post_list}
        return render(request, 'share/joined.html', context)





















def detail(request, Post_id):
    post = get_object_or_404(Post, pk=Post_id)
    context = {'post': post}
    return render(request, 'share/productInfo.html', context)



    
    

def join(request, Post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk = Post_id)
        if request.user in post.joined_users.all():
            post.joined_users.remove(request.user)
            if post.participants != 0:
                post.participants -=1
            post.save()
        else:
            post.joined_users.add(request.user)
            post.participants +=1
            post.save()
        return redirect('share:index')
    else:
        return redirect('common:login')


    

def Delete(request, Post_id):
    post = get_object_or_404(Post, pk = Post_id)
    post.delete()
    return redirect('share:cart')


def create(request):
    if request.method == "POST":

        post=Post(  user=request.user,
                    # category=request.POST.get('category'),
                    title=request.POST.get('title'),
                    price=request.POST.get('price'),
                    participants=0,
                    recruit_num=request.POST.get('recruit_num'),
                    category=Category.objects.get(sort=request.POST.get('category')),
                    dicount_price=request.POST.get('dicount_price'),
                    content=request.POST.get('content'),
                    image=request.FILES.get('image'))
        post.save()
        return redirect('share:index')
    else:
        return render(request, 'share/group.html')
    
def modify(request , Post_id):
    post = Post.objects.get(id = Post_id)
    if request.method == 'POST':
        post.title = request.POST['title']
        post.price = request.POST['price']
        post.content = request.POST['content']
        post.category=Category.objects.get(sort=request.POST.get('category'))
        post.recruit_num = request.POST['recruit_num']
        post.dicount_price = request.POST['dicount_price']
        post.image = request.FILES.get('image')
        post.save()
        return redirect('share:cart')
    else:
        post = Post.objects.get(id=Post_id)
        context = {'post': post}
        return render(request, 'share/Product_modify.html',context)
    

templates/share/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="myPage.css">
    <link rel="stylesheet" href="joined.css">
    <link rel="stylesheet" href="home.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Grape+Nuts&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'joined-style.css' %}?after">
    <title>Cart</title>
</head>

<body>
    <div class="sideNav" style="top:0; left:0">
        <header>My Page</header>
        <img src="{% static 'images/user.png' %}" alt="" id="userImg">
        <ul>
            <li><a href="/share/" id="pagename">Home</a></li>
            <li><a href="{% url 'share:joined' %}" id="joined">Joined Group</a></li>
            <li><a href="{% url 'share:cart' %}"><b>Created Group</b></a></li>
            <li><a href="{% url 'common:editinfo' %}">Edit Information</a></li>
            <li><a href="{% url 'common:editpw' %}">Edit Password</a></li>
            {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'common:logout' %}">logout</a></li>
            {% endif %}     
        </ul>
    </div>
    <div class="contents">
        <div id="joinedGroup">
            <h2 style="margin-left: 10px;">Created Group</h2>

            <div id="box">
                <div id="error">
                    There is no product!
                </div>
                    {% for Post in Post_list %}
                        {% if Post.user == user %}
                        <article class="book">
                            {% if Post.image %}
                            <a href="/share/{{ Post.id }}/"><img src="{{Post.image.url}}" class="bookImage" alt="book"></a>
                            {% else %}
                            <a href="/share/{{ Post.id }}/"><img src="{% static 'images/default.jpg' %}" class="bookImage" alt="book"></a>
                            {% endif %}
                            <div class = "contents_bottom">
                                <div class="bookName">
                                    <div>{{Post.title}}</div>
                                </div>

                                <progress value={{Post.participants}} max={{Post.recruit_num}}></progress>

                                <div class="bookPrice">
                                    <div class="bookPersonnel"><p style="margin: 0;">recruit : {{Post.recruit_num}} / participant : {{Post.participants}} </p></div>
                                    <span style="color:balck"> <del style="color:rgb(180, 179, 179); font-size: 13px;">{{Post.price}}</del>{{Post.dicount_price}}</span>
                                </div>
                                <div id = control_btn_box>
                                    <div>
                                        <button class="control_btn" value="delete" onclick = "location.href = '{%url 'share:modify' Post.id %}'">MODIFY</button>
                                    </div>
                                    <div>
                                        <form action = "{% url 'share:Delete' Post.id %}" method="post">
                                            {%csrf_token %}
                                            <button class="control_btn" value="delete">DELETE</button>
                                        </form>
                                    </div>
                                    
                                    
                                </div>
                            </div>

                        </article>
                        {% endif %}
                    {% empty %}
                        <div>상품이 없습니다!</div>
                    {% endfor %}
            </div>

        </div>

    </div>
</body>

</html>

templates/share/joined.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Grape+Nuts&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'joined-style.css' %}?after">
    <title>Joined Group</title>
</head>

<body>
    <div class="sideNav" style="top:0; left:0">
        <header>My Page</header>
        <img src="{% static 'images/user.png' %}" alt="" id="userImg">
        <ul>
            <li><a href="/share/" id="pagename">Home</a></li>
            <li><a href="{% url 'share:joined' %}" id="joined"><b>Joined Group</b></a></li>
            <li><a href="{% url 'share:cart' %}">Created Group</a></li>
            <li><a href="{% url 'common:editinfo' %}">Edit Information</a></li>
            <li><a href="{% url 'common:editpw' %}">Edit Password</a></li>
            {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'common:logout' %}">logout</a></li>
            {% endif %}     
        </ul>
    </div>
    <div class="contents">
        <div id="joinedGroup">
            <h2 style="margin-left: 10px;">Joined Group</h2>

            <div id="box">
                <div id="error">
                    There is no product!
                </div>
                    {% for Post in Post_list %}
                        {% if request.user in Post.joined_users.all %}
                        <article class="book">
                            {% if Post.image %}
                            <a href="/share/{{ Post.id }}/"><img src="{{Post.image.url}}" class="bookImage" alt="book"></a>
                            {% else %}
                            <a href="/share/{{ Post.id }}/"><img src="{% static 'images/default.jpg' %}" class="bookImage" alt="book"></a>
                            {% endif %}
                            <div class = "contents_bottom">
                                <div class="bookName">
                                    <div>{{Post.title}}</div>
                                </div>

                                <progress value={{Post.participants}} max={{Post.recruit_num}}></progress>

                                <div class="bookPrice">
                                    <div class="bookPersonnel"><p style="margin: 0;">목표 인원: {{Post.recruit_num}} / 담은 인원 : {{Post.participants}} </p></div>
                                    <span style="color:balck"> <del style="color:rgb(180, 179, 179); font-size: 13px;">{{Post.price}}</del>{{Post.dicount_price}}</span>
                                </div>

                            </div>

                        </article>
                        {% endif %}
                    {% empty %}
                        <div>상품이 없습니다!</div>
                    {% endfor %}
            </div>

        </div>

    </div>
</body>

</html>

templates/share/main.html
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<html lang="en">
<head>
    <meta chrarset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Grape+Nuts&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300&display=swap" rel="stylesheet">


    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <title>main-page</title>
</head>

<body>
<div id="wrap">
    <header>
        {% if user.is_authenticated %}
        <div id="sharebox">
            <a href="{%url 'share:create' %}" id="share"><b>LET'S<br>START</b></a>
        </div>
        {% endif %}
        <h1><a href="/share/" id="pagename">SHARESHARE</a></h1>

        <nav>
            {% if user.is_authenticated %}
            <a href="{%url 'share:cart' %}" id="cart">CART</a>
            {% endif %}
            
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logout' %}">LOGOUT</a>
            {% else %}
            <a class="nav-link" href="{% url 'common:login' %}">LOGIN</a>
            {% endif %}
            
        </nav>

    </header>

        <div id="category">
            <a href="{% url 'share:category' 1%}" id="Food">Food</a>
            <a href="{% url 'share:category' 2 %}">Book</a>
            <a href="{% url 'share:category' 3 %}" id="Stationery">Stationery</a>
            <a href="{% url 'share:category' 4 %}" id="Clothes">Clothes</a>
            <a href="{% url 'share:category' 5 %}" id="Etc">Etc</a>
        </div>

<div id="contentbox">
    <div id="contenthead">
        <div style="width:100%">
            <div class="search-bar" >
                <i class="fas fa-search"></i>
                {% comment %} 버튼 엔터키  {% endcomment %}
                <input class="search-bar__input" type="search" id="search_kw" value="{{ kw|default_if_none:'' }}" onkeypress="return search(event)" placeholder="search" />
                {% comment %} 버튼 클릭 {% endcomment %}

                {% comment %} 찾기 버튼 이미지 {% endcomment %}
                <button style="position:relative; left:25px;" class="btn btn-outline-secondary" type="button" id="btn_search"><img alt="search"  style="width:20px"  src="{%static 'images/search_icon.png'%}"></button>
             </div>
        </div>
        {% comment %} <form id="form" method="get" action=""> {% endcomment %}
            <select name="sort" id="sort" onchange="location = this.value;">
                <option class="sort-recent" value ="?sort=recent">recent</option>
                <option class = 'sort-like' value="?sort=like">like</option>
                <option class = 'sort-Top_price' value="?sort=Top_price">Top price</option>
                <option class = 'sort-Low_price' value="?sort=Low_price">Low price</option>
            </select>
        {% comment %} </form>   {% endcomment %}
        
    </form>
    </div>
    <div id="contents">
        {% if Post_list %}
            {% for Post in Post_list %}

            <article>
                {% if Post.image %}
                <a href="/share/{{ Post.id }}/"><img src="{{Post.image.url}}" alt="book"></a>
                {% else %}
                <a href="/share/{{ Post.id }}/"><img src="{% static 'images/default.jpg' %}" alt="book"></a>
                {% endif %}
                <div class = "contents_bottom">
    
                    <div class="book_name">
                        <span id = "titlename">{{Post.title}}</span>


                        {% if user in Post.like.all %}


                        <form action = "{% url 'share:like' Post.id%}" method="post">
                        {%csrf_token %}
                        <button class="like" value="like">
                            <img  src="{% static 'images/heartred.png' %}" alt="heart">{{Post.like_num}}
                        </button>
                        </form>
                        {% else %}
                        <form action = "{% url 'share:like' Post.id%}" method="post">
                            {%csrf_token %}
                        <button class="like" value="unlike">
                            <img  src="{% static 'images/heart.png' %}" alt="blank_heart">{{Post.like_num}}
                        </button>

                        </form>
                        {% endif %}


                    </div>
    
                    <div class="prog">
                        <progress value={{Post.participants}} max={{Post.recruit_num}}></progress>
                    </div>
    
                    <div class="price">
                        <div class="personbox"><img src="{% static 'images/person.png' %}" alt="person" class="person"> <p style="margin: 0;">{{Post.participants}}/{{Post.recruit_num}}</p></div>
                        <span style="color:balck"> <del style="color:rgb(180, 179, 179); font-size: 13px;">{{Post.price}}  </del>  {{Post.dicount_price}}</span>
                    </div>
    
                </div>
            </article>
            {% endfor %}
        {% else %}
            <p>상품이 없습니다....</p>
        {% endif %}


    </div>
</div>

{% comment %} <div class="pagenumberblock">
    <a href=""> <b>1</b> </a>
    <a href=""> 2 </a>
    <a href=""> 3 </a>
    <a href=""> 4 </a>

</div> {% endcomment %}



{% comment %} 페이징처리 시작 {% endcomment %}
<ul class="pages" style="list-style: none;">
    {% comment %} 이전페이지 {% endcomment %}
    {% if Post_list.has_previous %}
    <li class="pages-li">
        <a href="?page={{ Post_list.previous_page_number }}">Prev</a>
    </li>
    {% else %}
    <li>
        <a href="#" tabindex="-1" aria-disabled="true" style="color: grey;">Prev</a>
    </li>
    {% endif %}


    {% comment %} 페이지 리스트 {% endcomment %}
    {% for page_number in Post_list.paginator.page_range %}
    {% if page_number == question_list.number %}
        <li class="pages-li">
            <a class="page-item" href="?page={{ page_number }}"  style="color: grey;">{{ page_number }}</a>
        </li>
    {% else %}
        <li>
            <a href="?page={{ page_number }}" tabindex="-1"  style="color: grey;">{{ page_number }}</a>
        </li>
    {% endif %}
    {% endfor %}


    {% comment %} 다음페이지 {% endcomment %}
    {% if Post_list.has_next %}
        <li class="page-li">
            <a href="?page={{ Post_list.next_page_number }}"  style="color: grey;">Next</a>
        </li>
    {% else %}
        <li>
            <a href="#" tabindex="-1" aria-disabled="true" style="color: grey;">Next</a>
        </li>
    {% endif %}
</ul>
{% comment %} 페이징처리 끝 {% endcomment %}




<form id="searchForm" method="get" action="">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});

{% comment %} 버튼 엔터키 {% endcomment %}
function search(e) {
    if (e.keyCode == 13) {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
    }
}

//셀렉트 유지
var getUrlParameter = function getUrlParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;

    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : sParameterName[1];
        }
    }
};

$(document).ready(function(){
  var sort = getUrlParameter('sort');
  if(sort == 'like'){
    $('.sort-like').prop('selected', 'selected')
  }else if(sort == 'Top_price'){
    $('.sort-Top_price').prop('selected', 'selected')
  }else if(sort == 'Low_price'){
    $('.sort-Low_price').prop('selected', 'selected')
  }
  else{
    $('.sort-recent').prop('selected', 'selected')
  }
});


</script>
{% endblock %}




</div>
    <div id="finish">
        <footer class="footer" style="position: absoloute; bottom:0;">
            <h1><a href="/share" id="pagename">SHARESHARE</a></h1>
            <div>
            This is Team TAG's Project!!<br>
            최락원, 김민수, 이은서, 변승진, 이은지, 유종혁
            </div>
        </footer>
    </div>

</body>


</html>

templates/share/productInfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'productInfo.css'%}?after">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">

    <title>Product Information</title>
</head>
<body>
    <header>
        {% if user.is_authenticated %}
        <div id="sharebox">
            <a href="{%url 'share:create' %}" id="share"><b>LET'S<br>START</b></a>
        </div>
        {% endif %}
        <h1><a href="/share/" id="pagename">SHARESHARE</a></h1>

        <nav>
            {% if user.is_authenticated %}
            <a href="{%url 'share:cart' %}" id="joined" >CART</a>
            {% endif %}


            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logout' %}">LOGOUT</a>
            {% else %}
            <a class="nav-link" href="{% url 'common:login' %}">LOGIN</a>
            {% endif %}
        </nav>
    </header>

    <div class="gridContainer" style="margin-top: 200px; margin-bottom: 200px;">
        <div class="leftMargin"></div>
        <div class="left">
            <div class="productImg">
                {% if post.image %}
                <img src="{{post.image.url}}" alt="image">
                {% else %}
                <img src="{% static 'images/default.jpg' %}" alt="image">
                {% endif %}
                
                <button><img src="/img/see.png" alt=""></button>
            </div>
            <div>
                <div class="comment">
                    <p style="font-weight:700;">Comment</p>
                    <p style="padding: 5px; font-weight: 300;">{{post.content}}</p>
                </div>
            </div>
        </div>
        <div class="middle"></div>
        <div class="right">
            <div class="productName">{{post.title}}</div>
            <div class="price">
                <div class="currentPrice">{{post.dicount_price}}</div>
                <div class="originalPrice">{{post.price}}</div>
                <div class="priceMargin"></div>
            </div>
            <div class="person">
                <div class="personName">{{post.user.username}} / {{post.user.last_name}}{{post.user.first_name}}</div>
                <img src= "{% static 'images/person.png' %}" alt="" class="personKakao">
            </div>
            <div class="productProgress">
                <progress value={{post.participants}} max={{post.recruit_num}}></progress>
                <div style="display: inline;font-size: 30px; font-weight: 500;"><p style ="text-align: right; margin:0px">{{post.participants}} / {{post.recruit_num}}명</p></div>
            </div>
            <div class="submitButtons">
                {% if user in post.joined_users.all %}
                <form action = "{% url 'share:join' post.id %}" method="post">
                    {%csrf_token %}
                    <button class="joinButton" value="disjoin">Disjoin</button>
                </form>
                {% else %}
                <form action = "{% url 'share:join' post.id %}" method="post">
                    {%csrf_token %}
                    <button class="joinButton" value="join">join</button>
                </form>
                {% endif %}
                

            </div>

        </div>
        <div class="rightMargin"></div>
    </div>
    <div id="finish">
        <footer class="footer">
            <h1><a href="share/" id="pagename">SHARESHARE</a></h1>
            <div>
            This is Team TAG's Project!!<br>
            최락원, 김민수, 이은서, 변승진, 이은지, 유종혁
            </div>
        </footer>
    </div>
</body>
</html>